// Copyright 2026 Marcelo Cantos
// SPDX-License-Identifier: Apache-2.0

//! Line-by-line parser for Homebrew Ruby formula files.
//!
//! Parses the subset of the Ruby DSL used by most tap formulae,
//! especially those generated by Homebrew Releaser. Does NOT require
//! a Ruby interpreter.

use std::path::Path;

/// A parsed tap formula.
#[derive(Debug, Clone)]
pub struct TapFormula {
    pub name: String,
    pub desc: Option<String>,
    pub homepage: Option<String>,
    pub version: String,
    pub license: Option<String>,
    pub url: String,
    pub sha256: String,
    pub platform_overrides: Vec<PlatformOverride>,
    pub dependencies: Vec<String>,
    pub build_dependencies: Vec<String>,
    pub install_steps: Vec<InstallStep>,
}

/// A platform-specific override for URL and SHA256.
#[derive(Debug, Clone)]
pub struct PlatformOverride {
    pub os: Option<String>,   // "macos" or "linux"
    pub arch: Option<String>, // "arm" or "intel"
    pub url: String,
    pub sha256: String,
}

/// An install directive from the `def install` block.
#[derive(Debug, Clone)]
pub enum InstallStep {
    BinInstall {
        source: String,
        target: Option<String>,
    },
    ManInstall {
        source: String,
        section: u8,
    },
    BashCompletion {
        source: String,
        target: Option<String>,
    },
    ZshCompletion {
        source: String,
        target: Option<String>,
    },
}

/// Parser state for tracking nested `on_*` blocks.
#[derive(Debug, Clone)]
enum ParserContext {
    TopLevel,
    OnPlatform { os: Option<String> },
    OnPlatformArch { os: Option<String>, arch: String },
    Install,
}

/// Parse a Ruby formula file.
pub fn parse_formula_file(path: &Path) -> anyhow::Result<TapFormula> {
    let content = std::fs::read_to_string(path)?;
    parse_formula(&content)
}

/// Parse formula content from a string.
pub fn parse_formula(content: &str) -> anyhow::Result<TapFormula> {
    let mut name = String::new();
    let mut desc: Option<String> = None;
    let mut homepage: Option<String> = None;
    let mut version = String::new();
    let mut license: Option<String> = None;
    let mut url = String::new();
    let mut sha256 = String::new();
    let mut platform_overrides: Vec<PlatformOverride> = Vec::new();
    let mut dependencies: Vec<String> = Vec::new();
    let mut build_dependencies: Vec<String> = Vec::new();
    let mut install_steps: Vec<InstallStep> = Vec::new();

    let mut context_stack: Vec<ParserContext> = vec![ParserContext::TopLevel];

    // Temporary storage for platform override being built.
    let mut pending_url: Option<String> = None;
    let mut pending_sha256: Option<String> = None;

    for line in content.lines() {
        let trimmed = line.trim();

        // Skip empty lines and comments.
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        // Class declaration.
        if trimmed.starts_with("class ") && trimmed.contains("< Formula") {
            // Extract class name: "class Mk < Formula" -> "mk"
            if let Some(class_name) = trimmed
                .strip_prefix("class ")
                .and_then(|s| s.split_whitespace().next())
            {
                name = camel_to_snake(class_name);
            }
            continue;
        }

        // Handle block openings.
        if trimmed == "on_macos do" {
            flush_pending_override(
                &mut platform_overrides,
                &context_stack,
                &mut pending_url,
                &mut pending_sha256,
            );
            context_stack.push(ParserContext::OnPlatform {
                os: Some("macos".into()),
            });
            continue;
        }
        if trimmed == "on_linux do" {
            flush_pending_override(
                &mut platform_overrides,
                &context_stack,
                &mut pending_url,
                &mut pending_sha256,
            );
            context_stack.push(ParserContext::OnPlatform {
                os: Some("linux".into()),
            });
            continue;
        }
        if trimmed == "on_arm do" {
            flush_pending_override(
                &mut platform_overrides,
                &context_stack,
                &mut pending_url,
                &mut pending_sha256,
            );
            let os = current_os(&context_stack);
            context_stack.push(ParserContext::OnPlatformArch {
                os,
                arch: "arm".into(),
            });
            continue;
        }
        if trimmed == "on_intel do" {
            flush_pending_override(
                &mut platform_overrides,
                &context_stack,
                &mut pending_url,
                &mut pending_sha256,
            );
            let os = current_os(&context_stack);
            context_stack.push(ParserContext::OnPlatformArch {
                os,
                arch: "intel".into(),
            });
            continue;
        }
        if trimmed == "def install" {
            flush_pending_override(
                &mut platform_overrides,
                &context_stack,
                &mut pending_url,
                &mut pending_sha256,
            );
            context_stack.push(ParserContext::Install);
            continue;
        }

        // Handle block closing.
        if trimmed == "end" {
            flush_pending_override(
                &mut platform_overrides,
                &context_stack,
                &mut pending_url,
                &mut pending_sha256,
            );
            if context_stack.len() > 1 {
                context_stack.pop();
            }
            continue;
        }

        // Parse directives based on current context.
        let current = context_stack
            .last()
            .cloned()
            .unwrap_or(ParserContext::TopLevel);

        match current {
            ParserContext::Install => {
                // Parse install directives.
                if let Some(step) = parse_install_line(trimmed) {
                    install_steps.push(step);
                }
                // Ignore unrecognised install lines (system calls, etc.).
            }
            _ => {
                // Parse metadata and platform blocks.
                if let Some(val) = extract_string_value(trimmed, "desc") {
                    if matches!(current, ParserContext::TopLevel) {
                        desc = Some(val);
                    }
                } else if let Some(val) = extract_string_value(trimmed, "homepage") {
                    if matches!(current, ParserContext::TopLevel) {
                        homepage = Some(val);
                    }
                } else if let Some(val) = extract_string_value(trimmed, "version") {
                    if matches!(current, ParserContext::TopLevel) {
                        version = val;
                    }
                } else if let Some(val) = extract_string_value(trimmed, "license") {
                    if matches!(current, ParserContext::TopLevel) {
                        license = Some(val);
                    }
                } else if let Some(val) = extract_string_value(trimmed, "url") {
                    match current {
                        ParserContext::TopLevel => {
                            url = val;
                        }
                        ParserContext::OnPlatform { .. } | ParserContext::OnPlatformArch { .. } => {
                            // Flush any previously pending override before starting a new one.
                            flush_pending_override(
                                &mut platform_overrides,
                                &context_stack,
                                &mut pending_url,
                                &mut pending_sha256,
                            );
                            pending_url = Some(val);
                        }
                        _ => {}
                    }
                } else if let Some(val) = extract_string_value(trimmed, "sha256") {
                    match current {
                        ParserContext::TopLevel => {
                            sha256 = val;
                        }
                        ParserContext::OnPlatform { .. } | ParserContext::OnPlatformArch { .. } => {
                            pending_sha256 = Some(val);
                        }
                        _ => {}
                    }
                } else if let Some((dep_name, is_build)) = parse_depends_on(trimmed) {
                    if is_build {
                        build_dependencies.push(dep_name);
                    } else {
                        dependencies.push(dep_name);
                    }
                }
            }
        }
    }

    // Flush any remaining pending override.
    flush_pending_override(
        &mut platform_overrides,
        &context_stack,
        &mut pending_url,
        &mut pending_sha256,
    );

    if name.is_empty() {
        anyhow::bail!("could not find class name in formula");
    }
    if version.is_empty() {
        anyhow::bail!("could not find version in formula '{name}'");
    }
    if url.is_empty() && platform_overrides.is_empty() {
        anyhow::bail!("could not find url in formula '{name}'");
    }

    Ok(TapFormula {
        name,
        desc,
        homepage,
        version,
        license,
        url,
        sha256,
        platform_overrides,
        dependencies,
        build_dependencies,
        install_steps,
    })
}

/// Convert CamelCase to snake_case (for formula class names).
/// "Mk" -> "mk", "MyFormula" -> "my_formula", "GnuTar" -> "gnu_tar"
fn camel_to_snake(s: &str) -> String {
    let mut result = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap_or(ch));
    }
    // Homebrew convention: AT becomes @, e.g. PythonAT3_12 -> python@3.12
    // But for simple cases, just lowercase is fine.
    result
}

/// Extract a string value from a line like `desc "some text"`.
fn extract_string_value(line: &str, keyword: &str) -> Option<String> {
    let rest = line.strip_prefix(keyword)?;
    let rest = rest.trim_start();
    // Handle both `keyword "value"` and `keyword("value")` forms.
    let quoted = if rest.starts_with('"') {
        rest
    } else if let Some(inner) = rest.strip_prefix('(') {
        inner.trim()
    } else {
        return None;
    };

    extract_quoted_string(quoted)
}

/// Extract content from a double-quoted string: `"content"` -> `content`.
fn extract_quoted_string(s: &str) -> Option<String> {
    let s = s.trim();
    if s.starts_with('"') && s.len() >= 2 {
        // Find the closing quote, handling escaped quotes.
        let inner = &s[1..];
        let mut result = String::new();
        let mut chars = inner.chars();
        loop {
            match chars.next() {
                Some('"') => return Some(result),
                Some('\\') => {
                    if let Some(escaped) = chars.next() {
                        result.push(escaped);
                    }
                }
                Some(c) => result.push(c),
                None => return None, // Unterminated string.
            }
        }
    }
    None
}

/// Parse a `depends_on` line.
/// Returns (name, is_build_dep).
fn parse_depends_on(line: &str) -> Option<(String, bool)> {
    let rest = line.strip_prefix("depends_on")?.trim_start();
    let name = extract_quoted_string(rest)?;

    // Check for `=> :build` or `=> :test` suffix.
    let is_build = rest.contains("=> :build");

    Some((name, is_build))
}

/// Parse an install directive line.
fn parse_install_line(line: &str) -> Option<InstallStep> {
    // `bin.install "binary_name"`
    // `bin.install "source" => "target"`
    if let Some(rest) = line.strip_prefix("bin.install") {
        let rest = rest.trim_start();
        return parse_install_with_rename(rest)
            .map(|(source, target)| InstallStep::BinInstall { source, target });
    }

    // `man1.install "file.1"` (or man2, man3, etc.)
    for section in 1..=9u8 {
        let prefix = format!("man{section}.install");
        if let Some(rest) = line.strip_prefix(&prefix) {
            let rest = rest.trim_start();
            let source = extract_quoted_string(rest)?;
            return Some(InstallStep::ManInstall { source, section });
        }
    }

    // `bash_completion.install "file" => "name"`
    if let Some(rest) = line.strip_prefix("bash_completion.install") {
        let rest = rest.trim_start();
        return parse_install_with_rename(rest)
            .map(|(source, target)| InstallStep::BashCompletion { source, target });
    }

    // `zsh_completion.install "file" => "name"`
    if let Some(rest) = line.strip_prefix("zsh_completion.install") {
        let rest = rest.trim_start();
        return parse_install_with_rename(rest)
            .map(|(source, target)| InstallStep::ZshCompletion { source, target });
    }

    None
}

/// Parse an install with optional rename: `"source"` or `"source" => "target"`.
fn parse_install_with_rename(s: &str) -> Option<(String, Option<String>)> {
    let source = extract_quoted_string(s)?;

    // Check for ` => "target"` suffix.
    if let Some(arrow_pos) = s.find("=>") {
        let after_arrow = s[arrow_pos + 2..].trim();
        if let Some(target) = extract_quoted_string(after_arrow) {
            return Some((source, Some(target)));
        }
    }

    Some((source, None))
}

/// Get the current OS from the context stack.
fn current_os(stack: &[ParserContext]) -> Option<String> {
    for ctx in stack.iter().rev() {
        match ctx {
            ParserContext::OnPlatform { os } => return os.clone(),
            ParserContext::OnPlatformArch { os, .. } => return os.clone(),
            _ => continue,
        }
    }
    None
}

/// Flush a pending platform override (URL + SHA256 pair) into the overrides vec.
fn flush_pending_override(
    overrides: &mut Vec<PlatformOverride>,
    context_stack: &[ParserContext],
    pending_url: &mut Option<String>,
    pending_sha256: &mut Option<String>,
) {
    if let (Some(url), Some(sha256)) = (pending_url.take(), pending_sha256.take()) {
        let current = context_stack.last();
        let (os, arch) = match current {
            Some(ParserContext::OnPlatformArch { os, arch }) => (os.clone(), Some(arch.clone())),
            Some(ParserContext::OnPlatform { os }) => (os.clone(), None),
            _ => (None, None),
        };
        overrides.push(PlatformOverride {
            os,
            arch,
            url,
            sha256,
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_camel_to_snake() {
        assert_eq!(camel_to_snake("Mk"), "mk");
        assert_eq!(camel_to_snake("MyFormula"), "my_formula");
        assert_eq!(camel_to_snake("GnuTar"), "gnu_tar");
        assert_eq!(camel_to_snake("ABC"), "a_b_c");
    }

    #[test]
    fn test_extract_string_value() {
        assert_eq!(
            extract_string_value(r#"desc "A cool tool""#, "desc"),
            Some("A cool tool".into())
        );
        assert_eq!(
            extract_string_value(r#"url "https://example.com/file.tar.gz""#, "url"),
            Some("https://example.com/file.tar.gz".into())
        );
        assert_eq!(extract_string_value("desc", "desc"), None);
    }

    #[test]
    fn test_extract_quoted_string() {
        assert_eq!(extract_quoted_string(r#""hello""#), Some("hello".into()));
        assert_eq!(
            extract_quoted_string(r#""hello \"world\"""#),
            Some(r#"hello "world""#.into())
        );
        assert_eq!(extract_quoted_string("noquotes"), None);
    }

    #[test]
    fn test_parse_depends_on() {
        assert_eq!(
            parse_depends_on(r#"depends_on "foo""#),
            Some(("foo".into(), false))
        );
        assert_eq!(
            parse_depends_on(r#"depends_on "bar" => :build"#),
            Some(("bar".into(), true))
        );
    }

    #[test]
    fn test_parse_install_line_bin() {
        match parse_install_line(r#"bin.install "my_binary""#) {
            Some(InstallStep::BinInstall { source, target }) => {
                assert_eq!(source, "my_binary");
                assert!(target.is_none());
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn test_parse_install_line_bin_rename() {
        match parse_install_line(r#"bin.install "my_binary" => "alias""#) {
            Some(InstallStep::BinInstall { source, target }) => {
                assert_eq!(source, "my_binary");
                assert_eq!(target, Some("alias".into()));
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn test_parse_install_line_man() {
        match parse_install_line(r#"man1.install "tool.1""#) {
            Some(InstallStep::ManInstall { source, section }) => {
                assert_eq!(source, "tool.1");
                assert_eq!(section, 1);
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn test_parse_install_line_completions() {
        match parse_install_line(r#"bash_completion.install "tool.bash" => "tool""#) {
            Some(InstallStep::BashCompletion { source, target }) => {
                assert_eq!(source, "tool.bash");
                assert_eq!(target, Some("tool".into()));
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn test_parse_full_formula() {
        let formula_text = r#"
class Mk < Formula
  desc "A build tool"
  homepage "https://github.com/example/mk"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/example/mk/releases/download/v0.8.0/mk-darwin-arm64.tar.gz"
      sha256 "aaaa1111bbbb2222cccc3333dddd4444eeee5555ffff6666777788889999aaaa"
    end
    on_intel do
      url "https://github.com/example/mk/releases/download/v0.8.0/mk-darwin-amd64.tar.gz"
      sha256 "bbbb2222cccc3333dddd4444eeee5555ffff666677778888"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/example/mk/releases/download/v0.8.0/mk-linux-arm64.tar.gz"
      sha256 "cccc3333dddd4444eeee5555ffff666677778888"
    end
    on_intel do
      url "https://github.com/example/mk/releases/download/v0.8.0/mk-linux-amd64.tar.gz"
      sha256 "dddd4444eeee5555ffff666677778888"
    end
  end

  depends_on "git"
  depends_on "cmake" => :build

  def install
    bin.install "mk"
    man1.install "mk.1"
    bash_completion.install "completions/mk.bash" => "mk"
    zsh_completion.install "completions/_mk"
  end
end
"#;

        let formula = parse_formula(formula_text).unwrap();
        assert_eq!(formula.name, "mk");
        assert_eq!(formula.desc, Some("A build tool".into()));
        assert_eq!(
            formula.homepage,
            Some("https://github.com/example/mk".into())
        );
        assert_eq!(formula.version, "0.8.0");
        assert_eq!(formula.license, Some("Apache-2.0".into()));

        assert_eq!(formula.platform_overrides.len(), 4);
        assert_eq!(formula.platform_overrides[0].os, Some("macos".into()));
        assert_eq!(formula.platform_overrides[0].arch, Some("arm".into()));
        assert!(formula.platform_overrides[0].url.contains("darwin-arm64"));

        assert_eq!(formula.dependencies, vec!["git"]);
        assert_eq!(formula.build_dependencies, vec!["cmake"]);

        assert_eq!(formula.install_steps.len(), 4);
        assert!(matches!(
            &formula.install_steps[0],
            InstallStep::BinInstall {
                source,
                target: None
            } if source == "mk"
        ));
        assert!(matches!(
            &formula.install_steps[1],
            InstallStep::ManInstall {
                source,
                section: 1
            } if source == "mk.1"
        ));
    }

    #[test]
    fn test_parse_formula_with_top_level_url() {
        let formula_text = r#"
class Simple < Formula
  desc "A simple tool"
  homepage "https://example.com"
  url "https://github.com/example/simple/archive/v1.0.0.tar.gz"
  sha256 "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
  version "1.0.0"
  license "MIT"

  def install
    bin.install "simple"
  end
end
"#;

        let formula = parse_formula(formula_text).unwrap();
        assert_eq!(formula.name, "simple");
        assert_eq!(formula.version, "1.0.0");
        assert_eq!(
            formula.url,
            "https://github.com/example/simple/archive/v1.0.0.tar.gz"
        );
        assert_eq!(
            formula.sha256,
            "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
        );
        assert!(formula.platform_overrides.is_empty());
    }

    #[test]
    fn test_parse_formula_missing_version() {
        let formula_text = r#"
class NoVersion < Formula
  desc "Missing version"
  url "https://example.com/file.tar.gz"
  sha256 "abcdef"
end
"#;
        assert!(parse_formula(formula_text).is_err());
    }

    #[test]
    fn test_parse_formula_missing_class() {
        let formula_text = r#"
desc "No class"
version "1.0"
"#;
        assert!(parse_formula(formula_text).is_err());
    }

    #[test]
    fn test_parse_formula_with_system_calls_ignored() {
        let formula_text = r#"
class Builder < Formula
  desc "A builder"
  version "2.0.0"
  url "https://example.com/builder.tar.gz"
  sha256 "abcdef1234567890"

  def install
    system "cmake", ".", *std_cmake_args
    system "make", "install"
    bin.install "builder"
  end
end
"#;

        let formula = parse_formula(formula_text).unwrap();
        assert_eq!(formula.name, "builder");
        // Only the bin.install should be captured; system calls are ignored.
        assert_eq!(formula.install_steps.len(), 1);
        assert!(matches!(
            &formula.install_steps[0],
            InstallStep::BinInstall { source, .. } if source == "builder"
        ));
    }
}
